env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:import/recommended
parserOptions:
  ecmaVersion: 13
  sourceType: module
rules:
  import/no-cycle: [2, {  ignoreExternal: true   }]
